title: Ajaxify - Shopify ajax pagination plugin
name: Ajaxify
description: Shopify ajax pagination plugin
subtitle: Shopify ajax pagination plugin
github_url: https://github.com/Elkfox/Ajaxify
download_url: https://github.com/Elkfox/Ajaxify/archive/master.zip
demo_url: https://ajaxify.myshopify.com/collections/all
